### ISSUE TITLE
Migrate from setup-tools to poetry

### ISSUE THREAD

**Issue by victor-iyi** [victor-iyi/word_sauce#4]
Migrate from `setup.cfg` to `pyproject.toml` using [poetry] as `build-backend`.

```toml
# Poetry build system. See: https://python-poetry.org/docs/pyproject/
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

---

## TODOS

- [x] Add [flake8], [mypy], [pytest], [pre-commit], [tox]
- [x] Use GitHub [workflows] & [actions]

[poetry]: https://python-poetry.org/docs/pyproject/
[flake8]: https://flake8.pycqa.org/en/latest/user/invocation.html
[mypy]: https://mypy.readthedocs.io/en/stable/config_file.html
[pytest]: https://docs.pytest.org/en/6.2.x/customize.html
[pre-commit]: https://pre-commit.com
[tox]: https://tox.wiki/en/latest/config.html
[workflows]: https://docs.github.com/en/actions/using-workflows
[actions]: https://docs.github.com/en/actions
